### PR TITLE
fix: nginx config from 'sites-enabled' instead of 'sites-available'

### PR DESCRIPTION
**Pull request by stefankoerner**

### CODE REVIEW

**Comment by maxpou** [comment]
Hi, can you provide more details please?

**Comment by SebTM** [comment]
I'm not the creator of the PR but I think I can explain it to you just as well:
As you can see in your nginx-Dockerfile (https://github.com/maxpou/docker-symfony/blob/master/nginx/Dockerfile) your are doing it really well by symlinking the symony-config to sites-enabled and removing the default config from there.

The Problem from know is that you are including all files under "/etc/nginx/sites-available/*" instead of "sites-enabled".

Another suggestion would be to extend the include-statement by only including "*.conf" files from "sites-enabled" as far as I know this whould be the default behaviour.

**Comment by davidbonachera** [comment]
In a more practical way it means thats if you can't match the server_name by adding the ip your host file, it will end up on the default config you did remove from /sites-enabled. But it's still present in a  /sites-available.

Run into a nginx config error and saw that.

**Comment by stefankoerner** [comment]
Sorry maxpou, i havn't seen your comment. It's exatly what SebTM answered. Thanks

**Comment by maxpou** [comment]
Great! 
Thanks @SebTM @davidbonachera @stefankoerner

**Pull request merged**
